### ISSUE TITLE
No context menu in others pages

### ISSUE THREAD

**Issue by kinokocorp** [PieterL75/netbox_contextmenus#1]
Hello,
Thank you for your great add-on.

I have a problem to display context menu when I try to go to page 2 etc... in devices page for example.
Same problem for prefixes page or other page with multipages.

This problem also occurs when I'm doing a quick search on the first page (devices/prefixes...).

NetBox version : 3.3.2

![image](https://user-images.githubusercontent.com/95225861/188475026-fbfb4bbf-5921-492a-b98e-e558edcf805d.png)

![image](https://user-images.githubusercontent.com/95225861/188475126-4a1392ac-d54a-421b-a747-e6b4f49719fb.png)

![image](https://user-images.githubusercontent.com/95225861/188475183-d19363f5-76c6-405c-add1-f153c97d3aa1.png)

**Comment by PieterL75** [comment]
I'm aware of this.
The problem is, that the addon is not aware of a re-render of the a page.

If you're good in javascript and know how to re-trigger the render, do give it a shot :-D

**Comment by kinokocorp** [comment]
Sorry, I don't have the necessary skills -_-
But I will check on forum or somewhere else

**Comment by PieterL75** [comment]
Glad to say that I found a nice way to fix this.
Please check the latest version for the new feature !
