### ISSUE TITLE
Delay menu

### ISSUE THREAD

**Issue by mindcloud69** [PieterL75/netbox_contextmenus#2]
Is there any way to add a delay when hovering over the burger before opening the menu?

**Comment by mindcloud69** [comment]
Added #3 to attempt to solve myself.

**Comment by PieterL75** [comment]
Looks like a nice feature, thx for taking time to implement..
I'll check the code and give feedback in the PR

**Comment by PieterL75** [comment]
I've used your input to update the code.. the pullrequest was not possible, as I rewrote quite some other stuff in the meantime..

released as v1.4.3 

Thx for the work though ! appreciated
