### ISSUE TITLE
Context menu not staying next to item further down page

### ISSUE THREAD

**Issue by sachenbachtherma** [PieterL75/netbox_contextmenus#6]
Netbox Version: 4.0.3
Context Menu Version: 1.4.1

Context menus do appear when hovering over the icon, however the context menu won't pop up next to the item after line 12, it will pop up next to item 12.  This is also the case if I scroll at all, the menu will pop up in the incorrect location.  This is true for all items that would have a context menu next to it (interfaces, cables, devices, etc.)

I have followed the installation instructions exactly as described in this git.

Here is an example picture:
![2024-06-10 09_47_49-Window](https://github.com/PieterL75/netbox_contextmenus/assets/172288042/ae9970c5-f19a-42ba-be9f-3bf54a08efaa)
I am hovering over the bottom context menu icon, however it pops up higher on the list than it should.

**Comment by PieterL75** [comment]
I cannot seem to reproduce this. I tested it on different screens, resolutions and dpi's.

**Comment by sachenbachtherma** [comment]
Is there any additional information I can provide that might help?

**Comment by PieterL75** [comment]
I was able to see the same..
I happens when you scroll in a list, and using v4.0+ of NetBox.
Probably has to do with the GUI overhaul.

Give me some time to check that out, and come up with a fix
