### ISSUE TITLE
Image Attachments on Devices Broken

### ISSUE THREAD

**Issue by sachenbachtherma** [PieterL75/netbox_contextmenus#7]
Hi, it appears that this plugin is causing issues with displaying image attachments on devices.  I don't know exactly when this started occurring as my instance of netbox is still being spun up, but I do know it worked at least 2 weeks ago and doesn't now.  See this issue that was opened on the Netbox GitHub:  https://github.com/netbox-community/netbox/discussions/16579.  Note I did not open that issue, however I am also experiencing it.

If you need any additional info let me know and i'll pull whatever debugs you need.

**Comment by kprklg** [comment]
Good afternoon
the problem is present

**Comment by PieterL75** [comment]
This should be fixed now. I tested it with the latest netbox_documents plugin, and the image show in the preview and when clicked
